### ISSUE TITLE
NameError: name 'z' is not defined

### ISSUE THREAD

**Issue by OctopusLian** [programming-book-practice/Python-Crash-Course-Homework#2]
运行7-10程序：
```py
name_prompt = "\nWhat's your name? "
place_prompt = "If you could visit one place in the world, where would it be? "
continue_prompt = "\nWould you like to let someone else respond? (yes/no) "

responses = {}

while True:
    name = input(name_prompt)
    place = input(place_prompt)

    responses[name] = place

    repeat = input(continue_prompt)
    if repeat != 'yes':
        break

print("\n--- Results ---")
for name, place in responses.items():
    print(name.title() + " would like to visit " + place.title() + ".")
```

报错信息  
```
$ python -u 7-10.py 

What's your name? z
Traceback (most recent call last):
  File "7-10.py", line 8, in <module>
    name = input(name_prompt)
  File "<string>", line 1, in <module>
NameError: name 'z' is not defined
```

**Comment by OctopusLian** [comment]
难道是因为输入的时候类型是"z"导致的，而不是`z`？

**Comment by OctopusLian** [comment]
把`input`换成`raw_input`就可以了。  
书上是python3版本，而我本机是python2版本。  
[网上教程简易python程序NameError: name 'xxx' is not defined？](https://www.zhihu.com/question/31388311)
