### ISSUE TITLE
super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by OctopusLian** [programming-book-practice/Python-Crash-Course-Homework#7]
练习 9-6,9-7,9-8时出现的错误  
```
Traceback (most recent call last):
  File "./Python-Crash-Course-Homework/chapter09/9-8.py", line 44, in <module>
    eric = Admin('eric', 'matthes', 'e_matthes', 'e_matthes@example.com', 'alaska')
  File "./Python-Crash-Course-Homework/chapter09/9-8.py", line 24, in __init__
    super().__init__(first_name, last_name, username, email, location)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by OctopusLian** [comment]
原因是该方法调用super()为在python3中的方法，而此是在python2中运行的。
